name: nir-coloring
channels:
  - conda-forge
dependencies:
  - python<3.10
  - pip
  - pip:
      - -e .
      - clean-fid
      - aiohttp
      - aiofiles
      - pandas
      - tqdm
      - pillow
      - astral
      - azure-storage-blob
      - python-dotenv
      - opencv-python
      - notebook
      - matplotlib
      - seaborn
      - kornia
      - torch
      - torchvision
      - threadpoolctl
      - scipy==1.11.1 #https://github.com/GaParmar/clean-fid/issues/53
      - pyiqa
      - jupyter
      - seaborn